### ISSUE TITLE
Feature: Release for latest version EF Core 2?

### ISSUE THREAD

**Issue by educielo** [scottksmith95/LINQKit#80] opened 2018-07-27 19:54 UTC
Is there any plan for release for .Net Core 2.2?
I have already added this package for a .Net Core 2.2 using the latest release but it gives me warning on my dependencies. Any future update for .Net Core 2,2?

**Comment by mahald** [comment] 2018-10-04 09:30
+, would be nice to have the library compiled with .NET Standard

**Comment by StefH** [comment] 2018-11-22 06:34
The .NET Standard 2.0 version (LinqKit.Microsoft.EntityFrameworkCore) has a dependency on `Microsoft.EntityFrameworkCore (>= 2.0.1)`, however when you just install a newer EF version, this should not be a problem?

**Comment by reberinformatik** [comment] 2018-11-26 09:19
Project target framework is .NET Core 2.1:
![image](https://user-images.githubusercontent.com/22144995/49004491-a7db7080-f164-11e8-849c-2caf40208507.png)

**Comment by StefH** [comment] 2018-11-26 12:50
@educielo and @reberinformatik 

I'm confused, what is your exact question or what does not work on your system ?

**Comment by educielo** [comment] 2018-11-29 13:13
I'm just getting a nasty compilation warning on the dependencies same as the screenshot above provided by @reberinformatik. It's nice to have a version that is compatible with .Net Core 2.1 or higher. I guess the one i have pulled has some dependencies. The library works as expected but the warning is a bit disturbing.

**Comment by StefH** [comment] 2018-11-30 08:35
I cannot reproduce, see my example project at : https://github.com/StefH/LinqKitExamples

**Comment by educielo** [comment] 2018-11-30 10:20
@StefH upon updating my visual studio and the latest .net sdk, the warning also went away.

**Comment by StefH** [comment] 2018-11-30 12:03
OK.

Closing.

**Closed by StefH** 2018-11-30 12:03 UTC
Labels: feature
