### ISSUE TITLE
Question - EF Core - AsExpandable & Include

### ISSUE THREAD

**Issue by rizi** [scottksmith95/LINQKit#146] opened 2021-09-16 18:07 UTC
Is AsExpandable working in combination with Include with EF Core 5.0? I'm completely confused, somehow it's working when I call Include before AsExpandable. But is this a known limitation or a bug?
And will this work for all use cases?

Br

**Comment by sdanyliv** [comment] 2021-11-29 20:22
Duplicate of https://github.com/scottksmith95/LINQKit/issues/147

**Closed** 2021-11-29 20:44 UTC
