### ISSUE TITLE
.NET Native Compiler error

### ISSUE THREAD

**Issue by peterjuras** [scottksmith95/LINQKit#47] opened 2016-08-14 19:26 UTC
Hi,

I'm trying to build a UWP in the release configuration with the .NET Native toolchain, but LINQKit appears to break it. The Compiler breaks as soon as LINQKit is referenced somewhere in the code. It throws the following error:

```
// Error List window
Internal compiler error: Sequence contains no elements

// Build output window
1>------ Build started: Project: NativeLinqkitTest, Configuration: Release x64 ------
1>  NativeLinqkitTest -> C:\Users\pjura\Desktop\NativeLinqkitTest\NativeLinqkitTest\bin\x64\Release\NativeLinqkitTest.exe
1>  Starting .NET Native compilation
1>  Processing application code
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): error : Internal compiler error: Sequence contains no elements
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

Sadly it doesn't provide any line number or file. The error happens for me when the .NET Toolchain is enabled on both x86 & x64, Targeting any version of Windows 10. The error happens on both the main LINQKit and the EFCore version. [LinqKit.Core](https://github.com/dopare/LinqKit.Core) does not throw this error.

Steps to reproduce:
1. Create a blank Universal Windows Application project
2. Add the nuget package for LINQKit or LINQKit.EFCore
3. Create a new method or override OnNavigatedTo in MainPage.xaml.cs
4. Write a line of code that will reference LINQKit, e.g.:

``` c#
IQueryable<string> set = null;
set.AsExpandable();
// OR
var x = PredicateBuilder.New<string>();
```
1. Set the project to Release configuration or enable the .NET Native toolchain in the project settings (enabled by default for the Release configuration)
2. Build the project => You should see the error.

Do you know any workaround?

Otherwise, thanks for LINQKit :)

**Comment by Thorium** [comment] 2016-08-16 09:48
Just to make clear: Is your problem that it doesn't report stacktrace on Release, or is your problem the empty set?

How about:
```
var set2 = new []{1,2,3}.AsQueryable();
set2.AsExpandable();
```

**Comment by peterjuras** [comment] 2016-08-16 10:04
I worded the issue poorly. The problem is that even code that is fine and runs without .NET Native enabled produces the compiler error when . NET Native is enabled.

That means that I can't use LINQKit if .NET Native is enabled.

**Comment by StefH** [comment] 2016-08-16 20:14
Related to ?
https://github.com/aspnet/PlatformAbstractions/issues/34
https://github.com/aspnet/EntityFramework/issues/5483

**Comment by StefH** [comment] 2016-08-18 06:56
I'm able to reproduce, however I don't have any clue or background on this.

**Comment by MattWhilden** [comment] 2016-09-26 22:27
Hello! I work on the .NET Native runtime and compiler team. A random walk of github issues finds me here. I'm able to reproduce this issue and will definitely investigate further.

In particular, this output from the compile step definitely looks like our issue:
"IlcInternals.targets(936,5): error : Internal compiler error: Sequence contains no elements"

Will try to follow up before the end of the day. Ping me if you don't hear from me though, can be easy to get distracted with other issues. :-)

**Comment by MattWhilden** [comment] 2016-09-27 00:19
So the issue is that the compiler goes looking for the method "GetTypeInfo" on the type "System.Reflection.IntrospectionExtensions" Normally, this is fine because we find IntrospectionExtensions in the .NET framework libraries and happily move on. Unfortunately, LINQKit has an empty type that is also called System.Reflection.IntrospectionExtensions and we bail out when we cannot find a GetTypeInfo method there.

I'll file an issue against the compiler to avoid issues like this. We have other places where we don't bind by full assembly+type+member identity and it would be nice to get those all cleaned up.

To get around this issue, it is probably as simple as expanding the ifdef [here](https://github.com/scottksmith95/LINQKit/blob/master/src/LinqKit/Utilities/IntrospectionExtensions.cs) so that the entire class goes away when built for newer .NET platforms. 

Hope that helps. Please let me know if you have any questions.

Sorry I didn't see this earlier. If y'all have any other issues with .NET Native/UWP please feel free to add me directly or reach out to us on email at dotnetnative@microsoft.com.

**Comment by StefH** [comment] 2016-09-27 06:07
I'll take a look, thanks for the detailed information.

**Comment by StefH** [comment] 2016-09-27 07:04
This proposal indeed solves the compilation error.
However I get 2 warnings:

> 2>C:\...\Github\LINQKit\examples\UWPExampleApp\Resources.System.Linq.Expressions.rd.xml(35): warning : ILTransform_0027: Method 'CreateLambda' within 'System.Linq.Expressions.Expression' could not be found.
> 2>C:\...\LINQKit\examples\UWPExampleApp\Resources.System.Linq.Expressions.rd.xml(91): warning : ILTransform_0027: Method 'ParameterIsAssignable' within 'System.Linq.Expressions.Expression' could not be found.
> 2>  Computing application closure and generating interop code

I don't know if these are serious?

**Comment by StefH** [comment] 2016-09-27 07:14
@peterjuras new NuGet packages are released, can you please test?

**Comment by peterjuras** [comment] 2016-09-27 07:15
I'm currently on vacation for the next two weeks, but I'll test it afterwards!

**Comment by StefH** [comment] 2016-09-27 17:07
@MattWhilden Can you please check if this issue is now solved?

**Comment by MattWhilden** [comment] 2016-09-27 18:21
Works now for me. The two warnings can be ignored and should go away if you update Microsoft.NETCore.UniversalWindowsPlatform to version 5.2.2.

Thanks for the quick work!

**Comment by StefH** [comment] 2016-09-27 18:47
@MattWhilden I did add the dependency to the `UWPExampleApp` project, but have still those warnings.

**Comment by MattWhilden** [comment] 2016-09-27 22:08
Hmmm. I'm on Update 3 of VS. New template. Update the UWP package to 5.2.2 then build. I don't see the warnings. I wonder what the difference in our setups is... Curious.

**Comment by MattWhilden** [comment] 2016-09-28 00:39
Can you post your project.json?

**Comment by StefH** [comment] 2016-09-28 05:34
project.json from the UWP is here : https://github.com/scottksmith95/LINQKit/blob/master/examples/UWPExampleApp/project.json

**Comment by StefH** [comment] 2017-03-21 11:07
@MattWhilden Any update? Else I close this one.

**Closed** 2017-10-28 12:09 UTC
