### ISSUE TITLE
Include(...) after AsExpandable()

### ISSUE THREAD

**Issue by artelk** [scottksmith95/LINQKit#14] opened 2015-02-18 19:08 UTC
I suppose it would be great to support this.
I believe the following lines should be added to ExpandableQuery<T> class:

public IQueryable[T] Include(string path) 
{ 
  return InnerQuery.Include(path).AsExpandable(); 
}

**Comment by Thorium** [comment] 2015-04-14 19:01
The lambda version of the Include should also be supported. It is better way to avoid typos.

I'm not very big fan of Include()-syntax as it can easily hide some complex joins.

**Comment by artelk** [comment] 2015-04-14 19:49
I have checked EF sources. The expression based Include calls the string based version. I belive the method above should be enough to make it work.

**Comment by Thorium** [comment] 2015-04-14 20:14
Include would need "where T : class" constraint to ExpandableQuery. What if your query returns e.g. Guids?

**Comment by Thorium** [comment] 2015-04-14 20:25
Ok I added ExpandableQueryIncludeExtension, that should be enough.
Sorry about the line-endings.

**Comment by artelk** [comment] 2015-04-14 20:55
Sorry, I meant it should be added to ExpandableQuery. EF uses reflection searching for such method. It is better to  test  that before. I will try that and make a pull request...

**Comment by satyajit-behera** [comment] 2015-09-20 07:47
@Thorium How to use the ExpandableQueryIncludeExtension method. with EF.

**Comment by Thorium** [comment] 2015-09-20 08:45
I usually use just pure join and not so much includes. :-)

**Comment by satyajit-behera** [comment] 2015-09-20 08:49
@Thorium Thanks.

**Comment by Jaben** [comment] 2015-09-21 14:08
@Thorium Any chance of this getting merged? I could use this feature.

**Comment by hbulens** [comment] 2015-09-22 09:46
When can we expect this to be released into a new Nuget package? I'm currently experiencing this issue.

**Comment by Thorium** [comment] 2015-09-22 16:15
Ping @scottksmith95 would you like to do the NuGet-package? There are PRs, what is your opinion about these? Although I'm not a big fan of those, I could accept...

**Comment by scottksmith95** [comment] 2015-09-28 14:40
@Thorium You are pretty much maintaining this more than me. My time is so limited now, I cannot spend much on it. If you are ok with the PRs, feel free to pull them in. You should also be able to release a new NuGet package. I am pretty sure I made you an admin/owner.

**Comment by Thorium** [comment] 2015-09-29 13:45
Merged.

**Comment by phobos2077** [comment] 2016-09-16 09:45
This issue is still not fixed as of version 1.1.7.2.

**Comment by gregtayl** [comment] 2016-10-12 01:02
I have also confirmed that this is still an outstanding issue on 1.1.7.2.

The following code passes in version 1.1.3.1, but raises an assertion in 1.1.7.2 since the include is ignored, and MyNavigationProperty remains null (I haven't tried other versions so it's not clear which version this regression was introduced):

`var entity = context.Set<MyEntity>().AsExpandable().Include(o => o.MyNavigationProperty).Single();
Assert.IsNotNull(entity.MyNavigationProperty);`

Reversing the calls to Include/AsExpandable does appear to respect the call to include (and thus the assertion is not raised in 1.1.7.2), however, at least in our application this is not a trivial change to make. Ideally Include would be respected regardless of the order in which Include/AsExpandable are invoked.

**Comment by StefH** [comment] 2016-10-12 05:27
Hi @gregtayl , @phobos2077.

Since version **1.1.3.1**, this project was split into three projects:

- http://www.nuget.org/packages/LinqKit/
- http://www.nuget.org/packages/LinqKit.EntityFramework/
- http://www.nuget.org/packages/LinqKit.Microsoft.EntityFrameworkCore/

Can you indicate which version you are using ?

**Comment by gregtayl** [comment] 2016-10-13 21:46
@StefH thank you for point that out, I was unaware that there were different versions. 

I can confirm that calls to Include are respected when using LinqKit.EntityFramework.

**Comment by StefH** [comment] 2016-10-15 09:56
This breaking change in compatibility has also been discussed in this issue #49 .

The ideas are to bring back the dependency on **EF 6.x** into the **LinqKit** NuGet package. However my personal preference is to keep it like it's now, better package structure/naming and separation.

The downside is that indeed there are breaking changes if users just upgrade 1.1.2 to a later version which leads into questions like this issue or the issue #49.

I'll continue thinking on how to solve this.

**Comment by jag43** [comment] 2018-02-07 11:34
Do you have an update on this? `Include` also doesn't work with the EF Core version. See here for example https://stackoverflow.com/questions/48661790/includes-doesnt-work-with-linqkit-asexpandable

**Comment by pfeigl** [comment] 2018-05-14 07:10
Are there any plans how this can be addressed? Is LinqKit going to extend EntityQueryProvider or is that not an option? Should we create a Ticket with EFCore to enable other query providers? 

Ideally EFCore would have an interface which can be implemented which they check instead of just checking EntityQueryProvider.

**Comment by vertonghenb** [comment] 2018-05-19 01:11
Just my 2 cents but reading the EF Core docs, it shows the following:
**Ignored includes**

_"If you change the query so that it no longer returns instances of the entity type that the query began with, then the include operators are ignored.
In the following example, the include operators are based on the Blog, but then the Select operator is used to change the query to return an anonymous type. In this case, the include operators have no effect."_

```
using (var context = new BloggingContext())
{
    var blogs = context.Blogs
        .Include(blog => blog.Posts)
        .Select(blog => new
        {
            Id = blog.BlogId,
            Url = blog.Url
        })
        .ToList();
}
```

Could this have something to do with the issue?

**Comment by jag43** [comment] 2018-05-21 08:01
@vertonghenb I don't think that is the issue because there is no `Select()` being used.

**Comment by jag43** [comment] 2018-05-31 08:51
@StefH 

> Hi, sorry this took me so long to do. I have created a minimal repro here

Is this a sufficient demonstration?

**Comment by johnbouma** [comment] 2019-04-18 14:06
As a note, something related to this that I've seen is that owned types are not queried during the projection.  So if

Foo has one Bar
And Bar owns one baz (specifically in my case if Baz is in another table

And then your projection of Foo has a non projected Bar property, it will be null.  This dispite the fact that Bar owns Baz, and Baz would be included in any Bar returned from a query.

**Comment by keserwan** [comment] 2020-01-25 22:07
any one did a workaround on this?

**Comment by cjblomqvist** [comment] 2021-03-02 12:39
Most of the time the simple workaround is to put Includes before AsExpandable. This however makes it impossible to use filtered includes (as released in EF Core 5.0) - which would be really nice to be able to combine with LinqKit.

Anyway, just my 5 cents.

**Comment by sdanyliv** [comment] 2021-03-02 18:52
@cjblomqvist, create sample. I'll figure out what to do if it is possible.

**Comment by doboczyakos** [comment] 2022-02-20 15:13
@artelk / @StefH I think this one can be closed

**Closed** 2022-03-03 10:55 UTC
Labels: feature
